name: rietveld

channels:
  - defaults
  - conda-forge
  
dependencies:
  #Base MILK
  - tqdm=4.65.0
  - pip=22.1.2
  - prettytable=3.5.0
  - python=3.9
  - pandas=1.5.3
  - pydantic=1.10.8
  - seaborn=0.12.2
  - pyfai=2023.5.0
  - matplotlib=3.7.1
  - pyopencl=2023.1
  - opencv=4.6.0
  - pyqtgraph=0.13.1
  - autopep8=1.6.0
  - git=2.40.1

  # Spotlight
  - klepto=0.2.2
  - numpy=1.23.0
  # - openmpi
  # - mpi4py
  - jupyter=1.0.0
  - nbsphinx=0.8.9
  - sphinx=5.0.2
  - sphinxcontrib-programoutput=0.16
  - scipy=1.8.1
  - scikit-learn=1.1.2

  # pip packages
  - pip:
    #MILK github installation
    - -e ./
    #Spotlight
    - git+https://github.com/lanl/spotlight.git@v0.10.2
    - mystic==0.3.9
    - pyina==0.2.6
    - pathos==0.2.9
