name: Build and Publish Rietveld Docker Image

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/.github/workflows/build_Lin39.yml'
      - '**/.github/workflows/build_MacPy38_310.yml'
      - '**/.github/workflows/build_Win39.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
      - '**/.github/workflows/build_Lin39.yml'
      - '**/.github/workflows/build_MacPy38_310.yml'
      - '**/.github/workflows/build_Win39.yml'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-docker-image:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build container
        run: docker build -f Dockerfile -t rietveld .

  publish-container-image:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    needs: [build-docker-image]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push to local registry
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ env.REGISTRY }}/lanl/milk:${{ github.ref_name }}-${{github.sha}}
                                               